name: Build Vite Assets

on:
  push:
    paths:
      - 'resources/**'
      - 'vite.config.js'
      - 'package.json'
      - 'vite.config.ts'

jobs:
  vite:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install NPM dependencies
      run: npm install

    - name: Build Vite
      run: npm run build
